# Generated by Django 5.2.1 on 2025-12-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0003_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productimage',
            name='unique_primary_image_per_product',
        ),
        migrations.AddField(
            model_name='productimage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['is_deleted'], name='ecommerceap_is_dele_e1f350_idx'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('is_primary', True)), fields=('product',), name='unique_primary_image_per_product'),
        ),
    ]
