# Generated by Django 5.2.1 on 2025-12-24 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0004_remove_productimage_unique_primary_image_per_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name_plural': 'product images'},
        ),
        migrations.RemoveConstraint(
            model_name='productimage',
            name='unique_primary_image_per_product',
        ),
        migrations.RemoveIndex(
            model_name='productimage',
            name='ecommerceap_is_dele_e1f350_idx',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='is_deleted',
        ),
    ]
