# Generated by Django 5.2.1 on 2025-12-24 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0006_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name_plural': 'product images'},
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='is_deleted',
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'is_primary'], name='ecommerceap_product_b01308_idx'),
        ),
    ]
